name: Deploy with Capistrano

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - uses: miloserdow/capistrano-deploy@v2.2
        with:
          target: production
          enc_rsa_key_val: ${{ secrets.ENC_RSA_KEY }}
          deploy_key: ${{ secrets.DEPLOY_KEY }}
